# Generated by Django 4.1.3 on 2023-04-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_address_store_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store',
        ),
    ]
