# Generated by Django 4.1.3 on 2023-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('certificate', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
            ],
        ),
    ]
